language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./
after_success:
  - codecov
deploy:
  provider: s3
  access_key_id: "AKIAJE4YCWYVA3OIGA6Q"
  secret_access_key: "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"
  bucket: "group3section2bucket"
  skip_cleanup: true